function Jdot_f = Jdot_RRR(a_1,a_2,a_3,q_1,q_2,q_3,q_dot_1,q_dot_2,q_dot_3,theta,theta_dot)
%JDOT_RRR
%    JDOT_F = JDOT_RRR(A_1,A_2,A_3,Q_1,Q_2,Q_3,Q_DOT_1,Q_DOT_2,Q_DOT_3,THETA,THETA_DOT)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    31-Jan-2021 14:59:02

t2 = cos(theta);
t3 = sin(theta);
t4 = q_1+q_2;
t5 = q_dot_1+q_dot_2;
t6 = cos(t4);
t7 = t2.*theta_dot;
t8 = q_3+t4;
t9 = q_dot_3+t5;
t10 = sin(t4);
t11 = t3.*theta_dot;
t12 = cos(t8);
t13 = sin(t8);
t14 = -t7;
t15 = -t11;
t16 = a_2.*t5.*t6;
t17 = a_2.*t5.*t10;
t18 = a_3.*t9.*t12;
t19 = a_3.*t9.*t13;
t20 = -t16;
t21 = -t17;
t22 = -t18;
t23 = -t19;
Jdot_f = reshape([t20+t22-a_1.*q_dot_1.*cos(q_1),t21+t23-a_1.*q_dot_1.*sin(q_1),0.0,t14,0.0,t15,t20+t22,t21+t23,0.0,t14,0.0,t15,t22,t23,0.0,t14,0.0,t15],[6,3]);
